PR: Update shedule
PyConColombia/landing-page-2018 pull request #51
Opened 2017-11-06 14:16 UTC by rlaverde

Todavia faltan los  espacios de inscription..breaks  ..almuerzo

Creo que es mejor emergerlo  cuando  ya este el contenido de las charlas

![spectacle b10451](https://user-images.githubusercontent.com/2024217/32445092-bfb3d0ba-c2d2-11e7-9e8e-4936663a2671.png)

2017-11-06 14:23 UTC, goanpeca commented
@rlaverde yo subo el contenido de las charlas entonces para poder seguir con esto. Lo que no entiendo es el modelo de dates que hizo, cual es la necesidad de eso?

Lo que yo le decía era tener un modelo  `event.ini` y ahi poner fields que representaran las cosas.

Start Sprints - End Sprints
Start Tickets Sale - End Tickets Sale
Early Bird Until
Accept Proposals for Talk until
Accept Proposals for Talk from

Accept Proposals for Workshop until
Accept Proposals for Workshop from

etc...

Y usar esas entradas para mostrar u ocultar secciones.

2017-11-06 14:24 UTC, jhonjairoroa87 commented
Muchas gracias @rlaverde , se ve bastante bien! Totalmente deacuerdo contigo, el schedule es mejor unirlo cuando ya tengamos listo el schedule con los speakers definidos

2017-11-06 15:45 UTC, goanpeca requested changes
No necesitamos toda la complejidad de los dates, si no los vamos a usar para cosas mas interesantes.

Usar unos campos extras en el modelo de talks.ini para definir las fechas de comienzo y fin es suficiente

2017-11-06 16:18 UTC, goanpeca commented
```
# talks.ini
...

[fields.date_start]
label = Date and time of talk
type = date
width = 1/4

[fields.date_end]
label = Date and time of talk
type = date
width = 1/4
```

```
# en el template
{% for i in range((this.date_end - this.date_start).days + 1) %}
{{ this.date_start.fromordinal(this.date_start.toordinal() + i) }}
{% endfor %}
```

2017-11-06 22:26 UTC, goanpeca commented
@rlaverde mucho mejor, lo único es que el nombre del model `schedulle` no es muy claro,

2017-11-06 23:29 UTC, rlaverde commented
![spectacle qb9740](https://user-images.githubusercontent.com/2024217/32469385-68da93f2-c320-11e7-96eb-8d6da045116f.png)

2017-11-07 00:12 UTC, goanpeca commented
@rlaverde me parece raro que la hora salga a la izquierda en charla pero a la derecha en registro.

2017-11-07 00:13 UTC, goanpeca commented
En county podemos poner un combobox con la lista de paises?

2017-11-07 01:19 UTC, rlaverde commented
>me parece raro que la hora salga a la izquierda en charla pero a la derecha en registro.

Asi es el diseño

>En county podemos poner un combobox con la lista de paises?

Pues son muchos, tal vez podriamos hacer un plugin

2017-11-07 01:21 UTC, rlaverde commented
Ya añadi la imagen del ticket, pero el link no esta funcionando (por que es un svg), @goanpeca que hizo para que los del footer funcionaran?

![spectacle f12883](https://user-images.githubusercontent.com/2024217/32472278-df465e54-c32f-11e7-8f6a-72598d844302.png)

2017-11-07 01:32 UTC, goanpeca commented
@rlaverde lo guardó como plain svg ?

>Así es el diseño

De acuerdo, no me gusta ahora que lo veo es raro que se cambie la dirección.

2017-11-07 01:39 UTC, rlaverde commented
>lo guardó como plain svg ?

Lo acabo de hacer y sigue sin funcionar

2017-11-07 01:48 UTC, goanpeca commented
@rlaverde lo corrió con la `flag` de webpack?

`$ lektor server -f webpack` ?

2017-11-07 12:06 UTC, rlaverde commented
>lo corrió con la flag de webpack?

Si, ademas eso no influye

Ya encontré el error, las estrellas que se usan como background quedan encima de todo e impedían que todo lo de la primera sección fuera clickable

2017-11-07 12:14 UTC, rlaverde commented
Así se ve en una pantalla pequeña

![spectacle t15427](https://user-images.githubusercontent.com/2024217/32493278-46e13dda-c38b-11e7-9abe-91b3e53b28bb.png)

2017-11-07 12:56 UTC, rlaverde commented
Ya esta listo, incluso descative la seccion de call for speakers, y descative tambien el schedule (para activarlo cuando este este el contenido)

Lo unico que me preocupa es el color de las secciones, activando el schedule se ve asi:
![screenshot-2017-11-7 pycon colombia february 9 10 and 11 - 2018 medellin colombia](https://user-images.githubusercontent.com/2024217/32493850-65f1e0ba-c38d-11e7-9b7a-bfacadf8ff7d.png)

2017-11-07 13:43 UTC, goanpeca requested changes
@rlaverde gracias por los cambios.

1. Creo que no podemos tener secciones seguidas del mismo color. Hay que cambiar el color o re-ogranizar las secciones (como hicimos antes), para que queden intercaladas. El diseño que nos pasan es una guía y nosotros lo adaptamos a las necesidades.

2. No es muy claro que en móvil los `tabs` estén uno debajo del otro, en móvil debería ser un `dropdown` para escoger cada día, o verse igual (horizontal) que en desktop.

3. No es claro que la hora esté en lugares diferentes. Por favor ubiquemos la hora al mismo lado independientemente de si es inscripción o charla. Yo sugiero que a la izquierda siempre la hora.

2017-11-07 14:35 UTC, goanpeca commented
Y repito, no me gusta que la hora esté en lugares diferentes, por favor ubiquemos la hora al mismo lado independientemente de si es inscripción o charla

2017-11-07 14:42 UTC, goanpeca commented on models/room.ini
> +type = string
Ahora no es importante, pero eventualmente tal vez una foto y una descripción y un mapa debería incluirse. o Lat, Lon

2017-11-07 21:32 UTC, rlaverde commented on models/room.ini
> +type = string
Descripción,y una imagen, la ubicación no creo que funcione bien con latitud y longitud

2017-11-07 21:35 UTC, rlaverde commented
1. Como arreglamos lo del color? subir el schedule no me parece buena idea

2. Si un dropdown queda mejor

3. Al contrario me gusta el deseño con la hora aparte, hace mas clara la diferencia de que son los breaks

2017-11-07 23:10 UTC, goanpeca commented on models/room.ini
> +type = string
Lat/Lon es la única forma de mostrar un mapa de Google Maps de donde queda el edificio.

2017-11-07 23:11 UTC, goanpeca commented
>Como arreglamos lo del color? subir el schedule no me parece buena idea

Y qué sugiere?

>Al contrario me gusta el deseño con la hora aparte, hace mas clara la diferencia de que son los breaks

No me parece, se están mezclando las cosas, para eso eso tiene un ícono y un color, cambiar la posición cambia la idea que se quiere transmitir.

2017-11-08 14:38 UTC, rlaverde commented
>Y qué sugiere?

La parte de sponsors puede ser azul oscuro, e ir de ultimas

2017-11-08 15:44 UTC, goanpeca commented
@rlaverde POC ? imagen a ver como se ve?

2017-11-08 20:00 UTC, rlaverde commented
No se ve bien, tocaria cambiar el color de las imagenes. Podemos generalizar el css y asi hacer que el light-section dark-section (y una nueva white-section) fueran intercambiables.

y luego iterar las secciones y poner dark light white dark ligth white...

2017-11-08 20:13 UTC, goanpeca commented
>No se ve bien, tocaria cambiar el color de las imagenes. Podemos generalizar el css y asi hacer que el light-section dark-section (y una nueva white-section) fueran intercambiables.
y luego iterar las secciones y poner dark light white dark ligth white...

Ok hágale

---

Sobre lo de la hora, por favor ubique todas las horas, a la derecha o a la izquierda pero no una mezcla. eso no lo voy a negociar ;-)

2017-11-09 15:30 UTC, rlaverde commented
Merging, queremos testear la parte de tickets, los cambios de la agenda seran en otra PR

2017-11-09 15:31 UTC, merged